### ISSUE TITLE
[Bug] Extra characters in the French FATE world markers

### ISSUE THREAD

**Issue by krz0001** [una-xiv/umbra#40]
Weird "=" characters are displaying in the World Markers when using the French languafge with Umbra.
![image](https://github.com/una-xiv/umbra/assets/18511031/97c5288b-f8aa-463f-af22-dccf5af0cf80)

**Comment by krz0001** [comment]
Seems like this issue has returned with the 2.0 version of the plugin. 😅 
![image](https://github.com/user-attachments/assets/b62779d8-41aa-475e-97c5-796240edc5d4)

**Comment by haroldiedema** [comment]
Ah, thanks for letting me know! I'll have a look at it soon 😄

**Comment by haroldiedema** [comment]
Should be fixed again as soon as the next update it out in Dalamud.

**Comment by Tykku** [comment]
![image](https://github.com/user-attachments/assets/270206e9-4c37-4f7a-930c-a7c29e723b2a)
Still having issues not sure if related. This is in english

**Comment by GayPotatoEmma** [comment]
> ![image](https://private-user-images.githubusercontent.com/607260/369638587-270206e9-4c37-4f7a-930c-a7c29e723b2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NDExMjYsIm5iZiI6MTcyNjk0MDgyNiwicGF0aCI6Ii82MDcyNjAvMzY5NjM4NTg3LTI3MDIwNmU5LTRjMzctNGY3YS05MzBjLWE3YzI5ZTcyM2IyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxNzQ3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTY1M2Y2Y2IzNDVkNjAwZjFjYTk5NjgwNzM0YjcyYWU2ODY4YWU2NjMxZDhiMjZiZGM1YzhhYjdlZjU4ZDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X9NJU1QxXAsA_d_CygR8zDPmXJrSf3d8Di5YQ9ymsP4) Still having issues not sure if related. This is in english

Not related, change your world marker font settings to anything and then change it back, that should fix it.

**Comment by alexpado** [comment]
Pretty sure most of those are [Non-breaking Space](https://en.wikipedia.org/wiki/Non-breaking_space). It happens also with number separators. It should be probably reported upstream so the default Dalamud font can be fixed on this matter.

Regarding the screenshot above, it is really weird that ALL characters are affected.

**Comment by GayPotatoEmma** [comment]
No it's just a weird known issue that can be easily resolved by just swapping the world marker font back and forth. I have no idea why it happens either
